src/payment-request.ts
I hadn't actually appreciated that we were storing this value as a float in the passport. I think it would make sense to store this in pence and just convert to pounds for display purposes.
For now, I'm just doing a conversion here as this is a wider issue to address / refactor with a few outstanding questions...
- Do we need to update content to do calculations on pence?
- Do we just convert before writing the passport variable?
- How will this affect any active sessions?
- Do we just "cheat" and write a new passport variable which invite to pay handles (e.g. `application.fee.payable.pence`)?
=> fix: Convert payment amount to integer

src/payment-request.ts, src/types.ts
Branched off `dp/convert-amount-to-integer` so I can point to a single commit of all changes in `planx-new`
=> chore: Add `paidAt` and `createdAt` properties to `PaymentRequest` type

src/requests/payment-request.ts
The number of Pay nodes on an invite-to-pay flow is assumed to be exactly 1 as a temporary restriction until traversing the flow for a specific type is efficient.
=> workaround: limit request to pay to one pay node

pnpm-lock.yaml, src/export/bops/index.ts, src/export/bops/mocks/sections.ts, src/export/bops/tests/proposalDetails.test.ts, src/export/bops/tests/userRole.test.ts
This PR adds the `section_name` to metadata in the BOPS payload structure.
=> feat: Add `section_name` to BOPS payload

src/types/index.ts, src/types/planning-constraints.ts
for use in API & frontend changes over here https://github.com/theopensystemslab/planx-new/pull/1296 & https://github.com/theopensystemslab/planx-new/pull/1733
=> feat: add planning constraints types

.github/workflows/test.yml, pnpm-lock.yaml, src/export/bops/index.ts, src/export/bops/tests/payload.test.ts, src/export/oneApp/OneApp.test.ts, src/export/oneApp/model.ts, src/models/flags.ts, src/models/session/logic.test.ts
A few small fixes and updates that address linting and maintainability issues.
=> chore: Tidy-ups and package upgrades

src/export/bops/index.ts, src/types/component.ts
Follow on from https://github.com/theopensystemslab/planx-new/pull/1816
=> chore: Rename MFU

src/types/gov-uk-payment.ts
As part of the work outlined [here](https://github.com/theopensystemslab/planx-new/pull/1902) I'm pulling in types from a single source - they're currently replicated in planx-core, the API, and the Editor.
=> chore: Update GovPay types

src/export/bops/tests/applicationType.test.ts, src/export/bops/tests/works.test.ts, src/models/passport/passport.test.ts, src/models/passport/passport.ts, src/requests/payment-request.test.ts, src/types/session.ts
Required for https://github.com/theopensystemslab/planx-new/pull/2074
=> chore(types): Make `Passport.data` required property

src/export/bops/index.ts, src/export/bops/tests/constraints.test.ts, src/requests/export.ts, src/requests/flow.ts
- Fixes and edge case bug where a request for planning constraints returns an error
- Also addressed in [planx-new](https://github.com/theopensystemslab/planx-new/pull/2125)
- See ODP Slack for context - https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1692194583154089
=> fix: Handle edge case where constraints are missing

src/requests/user.ts, src/types/index.ts, src/types/roles.ts, src/types/user.ts
Helper method to be used as part of building a JWT for the user.
=> feat: Get user by email

package.json, src/requests/team.ts, src/requests/user.ts
A few basic helper functions to be used via the Swagger docs to make team management a non-dev task in the absence of a UI to allow self-management.
=> feat: Add/remove team members

src/requests/user.ts, src/types/user.ts
See comment here for context - https://github.com/theopensystemslab/planx-new/pull/2224#discussion_r1330510998
=> chore: Add team slug and name to `GetByEmail` request

package.json, pnpm-lock.yaml, src/export/bops/index.ts
Pleasee see https://github.com/theopensystemslab/planx-new/pull/2228
=> fix: Incomplete multi-character sanitation

package.json, pnpm-lock.yaml
Pointing at commit [8be92e4](https://github.com/theopensystemslab/planx-core/pull/135/commits/8be92e4a75fad346d3f9ffb0731efa089f467f3f) works for me - I can see a the schema file in my `node_modules`.
=> fix: Explicitly copy `schema.json` after build

src/requests/team.ts, src/types/team.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/2236
=> feat: Get team by slug

src/requests/user.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/2247
=> feat: `getById()` and `delete()` requests

src/export/digitalPlanning/model.ts
Apologies @jessicamcinchak - made this commit on https://github.com/theopensystemslab/planx-core/pull/78 and then never actually pushed 🤦 
Please see https://github.com/theopensystemslab/planx-core/pull/78#discussion_r1368495768 for context.
=> chore: Drop redundant non-null assertion operator from dates

src/templates/docx/LDCETemplate.ts, src/templates/docx/LDCPTemplate.ts
Changes directly correspond to feedback reported via linked Trello tickets, most applies to LDC-E but I updated LDC-P template for consistency wherever possible.
=> fix: update LDC form mappings

src/export/digitalPlanning/index.ts, src/export/index.ts
Small fix that might help resolve this issue which I keep hitting! https://github.com/theopensystemslab/planx-new/pull/2380#issuecomment-1817452818
No real rush to get this into `planx-new`, it can come along on the next update.
=> chore: Improve flow fetch errors

src/export/digitalPlanning/model.ts
Just to make `grep` a little easier in docker logs 👌
=> chore: Enrich error with `sessionId`

src/requests/user.ts
See https://github.com/theopensystemslab/planx-new/pull/2530 for full context
=> feat: Add `user.isStagingOnly()` function

src/requests/user.ts
Fixes https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1702296800034189
=> fix: account for `isStagingOnly` query returning empty users

src/export/digitalPlanning/model.ts, src/export/digitalPlanning/schema/schema.json, src/export/digitalPlanning/schema/types.d.ts
Updates types and passport mappings to match most recent schema release v0.2.2
=> chore: update digital planning schema types and mappings for v0.2.2

src/requests/team.ts
See https://github.com/theopensystemslab/planx-new/pull/2602
=> chore: Update `team.create()` to account for new `team_themes` table relationship

src/requests/team.ts, src/types/team.ts
This updates `planx-core` types to match new table added in https://github.com/theopensystemslab/planx-new/pull/2602
Implemented in https://github.com/theopensystemslab/planx-new/pull/2628
=> chore: Update `TeamTheme` type

src/requests/team.ts, src/types/index.ts, src/types/team.ts
- Updates types to reflect changes implemented in https://github.com/theopensystemslab/planx-new/pull/2646
- Exports `Team` types
=> chore: Update `team_themes` types

src/requests/team.ts, src/types/team.ts
- Adds new `team.updateTheme()` method
- Implemented in https://github.com/theopensystemslab/planx-new/pull/2660
=> feat: Add `team.updateTheme()`

src/templates/html/application/ApplicationHTML.tsx, src/templates/html/map/Map.tsx, src/templates/html/map/MapHTML.tsx
Will bump planx-core & map in one go over in planx-new once this merges because of type dependency, that will also pick up the boundary.html fix from earlier !
=> feat: bump `@opensystemslab/map` to v0.8.0

src/export/digitalPlanning/schema/schema.json, src/export/digitalPlanning/schema/types.d.ts
No passport mappings need to change with this one, just expanded data dictionaries / allowed values for enums!
Once merged, I'll add here so we can safely start querying & submitting new constraints: https://github.com/theopensystemslab/planx-new/pull/2710
=> chore: add odp schema v0.2.3 and re-generate types

src/export/bops/index.ts, src/export/bops/mocks/payload.ts, src/export/bops/mocks/sessionData.ts, src/export/bops/tests/files.test.ts, src/export/digitalPlanning/mocks/flows/planningPermission.ts, src/export/digitalPlanning/mocks/flows/priorApproval.ts, src/export/digitalPlanning/mocks/lawfulDevelopmentCertificate.ts, src/export/digitalPlanning/mocks/planningPermission.ts, src/export/digitalPlanning/mocks/priorApproval.ts, src/export/digitalPlanning/model.test.ts, src/export/digitalPlanning/schema/schema.json, src/export/digitalPlanning/schema/types.d.ts, src/export/oneApp/OneApp.test.ts, src/models/passport/mocks/index.ts, src/models/passport/passport.test.ts, src/templates/mocks/exampleLDCE.ts, src/templates/mocks/exampleLDCP.ts
Jess took this branch over! Key changes:
=> chore: Update file pasport names & bump to schema v0.3.0

src/models/passport/mocks/index.ts, src/models/passport/passport.test.ts
Reassuring that no code changes were needed here! Follow up from https://github.com/theopensystemslab/planx-core/pull/290#discussion_r1482991924
=> test: Add test example for `DrawBoundary` component

src/export/digitalPlanning/index.ts, src/export/digitalPlanning/model.test.ts, src/export/digitalPlanning/model.ts, src/export/index.ts, src/export/oneApp/OneApp.test.ts
See https://github.com/theopensystemslab/planx-new/pull/3021
=> feat: add debugging option to skip validation when generating DigitalPlanningPayload

src/requests/team.ts
See https://github.com/theopensystemslab/planx-new/pull/3040
=> feat: add Microsoft team integration types

src/requests/team.ts
planx-new db migration and updated sync script coming next
=> fix: account for separate staging & production columns for Power Automate API key in team integrations

src/export/digitalPlanning/model.ts, src/export/digitalPlanning/schema/schema.json, src/export/digitalPlanning/schema/types.d.ts
=> chore: update passport mappings to ODP Schema v0.6.0

src/export/digitalPlanning/model.ts
Testing on staging with freshest content & missed a couple variables
=> fix: adjust v0.6.0 schema mappings for preAssessment, ownership, and parking

src/export/digitalPlanning/model.ts
Reverts theopensystemslab/planx-core#390
E2E tests are failing in planx-new, revert this most recent change to rule out.
=> Revert "fix: account for manually answered planning constraints in ODP Schema generation"

src/export/digitalPlanning/index.ts, src/export/digitalPlanning/mocks/lawfulDevelopmentCertificate.ts, src/export/digitalPlanning/model.test.ts, src/export/digitalPlanning/model.ts, src/types/gov-uk-payment.ts
Bug reported here https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1717680689844139
=> fix: ensure invite-to-pay journeys correctly populate `application.fee.reference.govPay` in ODP Schema

src/requests/flow.ts
To match changes I have made in ``planx-new`` I have added the ``name`` column from the ``flows`` table to the shapes and functions defined here
This has been in order to fix E2E testing failures on ``planx-new`` to do with *rory/add-name-editor-2* changes.
=> feat: Adding Name Column Changes

package.json, pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-core/security/dependabot/8
=> fix: CVE-2024-4068

src/requests/team.ts, src/types/team.ts
This PR updates functions and types relating to ``team_settings`` with the new ``boundary_bbox`` column which replaces the previous ``boundary_json`` column: https://github.com/theopensystemslab/planx-new/pull/3375
=> feat: Add ``boundary_bbox`` to ``team_settings`` Types and Functions

package.json
Please see https://github.com/theopensystemslab/planx-new/pull/3359 for context
=> chore: Add `packageManager` property to `package.json`

src/export/digitalPlanning/schema/schema.json, src/export/digitalPlanning/schema/types.d.ts
As discussed, just importing new schema.json & regenerating types here - not actually updating any passport mappings yet as the applicable services are in internal testing only.
=> chore: ODP Schema v0.7.0

src/templates/generateExamples.ts, src/templates/html/Main.tsx, src/templates/html/application/ApplicationHTML.tsx, src/templates/html/map/Map.tsx, src/templates/html/map/MapHTML.tsx, src/templates/index.ts, src/types/component.ts
Small change to fix an import issue in [planx-new](https://github.com/theopensystemslab/planx-new) that appears when trying to bump to ESM.
=> [templates] extract DrawBoundaryUserAction to src/types

src/models/session/logic.test.ts, src/models/session/logic.ts
- Generates a path for a node, which is required for search
- Relies on https://github.com/theopensystemslab/planx-core/pull/462
- Implemented in https://github.com/theopensystemslab/planx-new/pull/3460
=> feat: `getPathForFlow()`

package.json, pnpm-lock.yaml
Resolves https://github.com/theopensystemslab/planx-new/security/dependabot/101
=> fix: CVE-2024-41818

src/models/session/logic.test.ts, src/models/session/logic.ts
Small bug I noticed when working on https://github.com/theopensystemslab/planx-new/pull/3650
=> fix: Update getPathForNode()

src/models/session/logic.ts, src/types/flow.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/3666
=> feat: Track internal portals when indexing nodes

src/export/bops/index.ts, src/types/component.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/3675
=> feat: Add `Page` component type

src/export/digitalPlanning/model.ts
Follows on from #515 & this latest submission error https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1727787479763779
=> fix: use fallback value for `applicant.siteContact.role` passport mappings

src/types/flow.ts
Please see https://opensystemslab.slack.com/archives/C5Q59R3HB/p1728371544101089
=> feat: Additional node tags

src/export/digitalPlanning/model.ts, src/types/flags.ts
Followup per auto-answers logic camp! 
Context in these threads: 
- `#planx` https://opensystemslab.slack.com/archives/C5Q59R3HB/p1728383135096849?thread_ts=1728241392.721639&cid=C5Q59R3HB
- `#planx-content` https://opensystemslab.slack.com/archives/C07F7215W7P/p1728461583943589
=> feat: add flagset for material change of use

src/types/index.ts, src/types/integrations.ts
Please see https://github.com/theopensystemslab/planx-new/pull/3843
=> feat: Add send integration types

src/export/bops/index.ts, src/types/component.ts
Trello ticket: https://trello.com/c/jEOLoubW/3034-can-we-introduce-in-house-end-of-service-feedback
=> feat: Add `Feedback` component type to enum

src/export/digitalPlanning/model.ts
Fixes https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1731513362475799
Latest release is hosted here https://theopensystemslab.github.io/digital-planning-data-schemas/v0.7.1/schemas/application.json
=> fix: account for new subdirectory in ODP Schema metadata

src/requests/flow.ts
This PR sets up work into Templates: https://trello.com/c/YjhjFaIQ/3111-templates-groundwork
Following work to add a `description` column to the `flows` table, I am not setting up work to add functionality to update it in the Editor
=> feat: Add `insertFlowDescription` Mutation

package.json, pnpm-lock.yaml, src/models/session/logic.test.ts, vitest.config.ts
Fixes https://github.com/theopensystemslab/planx-core/security/dependabot/15
=> fix: CVE-2025-24010

package.json, pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-core/security/dependabot/11
=> fix: CVE-2024-21538

src/export/digitalPlanning/mocks/flows/planningPermission.ts, src/export/digitalPlanning/mocks/flows/preApplication.ts, src/types/flow.ts
Per yesterday's templates call decision !
=> chore: rename "placeholder" tag to "customisation"

src/export/oneApp/model.ts
See thread https://opensystemslab.slack.com/archives/C089LL9LR5H/p1740137672736809
We previously updated ODP Schema mappings via https://github.com/theopensystemslab/planx-core/pull/552?email_source=slack, but failed to bring Uniform in alignment - which BOPS has pointed out !
=> fix: update Uniform descriptions to match ODP Schema

src/export/digitalPlanning/model.ts, src/export/digitalPlanning/schemas/application/schema.json, src/export/digitalPlanning/schemas/application/types.d.ts, src/export/digitalPlanning/schemas/preApplication/schema.json, src/export/digitalPlanning/schemas/preApplication/types.d.ts
**Changes:**
- Copies latest `application.json` & `preApplication.json` from schema repo, regenerates types
- Adds new `getCIL()`
- Updates `getOwners()`
=> chore: ODP Schema v0.7.3 passport mappings

src/export/digitalPlanning/model.ts
Per https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1740751686846139
=> fix: ensure correct boolean types in schema `Owners` mappings

src/export/digitalPlanning/mocks/lawfulDevelopmentCertificate.ts, src/export/digitalPlanning/model.ts
Per https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1740751686846139
=> fix: correct CIL condition

src/export/digitalPlanning/model.ts
JSONs already added, this just tidies up some mappings!
=> chore: v0.7.3 schema mapping adjustments

src/export/digitalPlanning/mocks/planningPermission.ts, src/export/digitalPlanning/model.ts
Per request from Meera at Lambeth - this one is a great example of a type we already had/have in the schema, but have never brought our passport mappings up to sync with ! We need to do this more pro-actively at some point !
See https://opendigitalplanning.slack.com/archives/C08BL63KCKB/p1741175213567829
=> feat: add materials mappings for schema

package.json, pnpm-lock.yaml
An attempt to address the following issue - 
I think the underlying issue is coming from how planx-core is installed and built within planx-new. I think a better approach here would be to either -
- Properly package planx-core
- Move to planx-new repo
To be disscused!
=> chore: Add back MUI base package

package.json, pnpm-lock.yaml
Reverts theopensystemslab/planx-core#690
This previous attempt appears to have made things worse - we're seeing more build errors in planx-new now.
=> Revert "chore: Add back MUI base package"

src/export/bops/utils/index.ts, src/export/bops/utils/mapAndLabel.ts, src/export/bops/utils/schema.ts
This PR adds validation for the `AddressInput` field added to the schema / list component in PlanX.
=> feat: Parse responses from `AddressInput` schema fields

src/requests/team.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/4588
Further details can be found here - https://github.com/theopensystemslab/planx-new/pull/4588/files#r2046563181
=> feat: Toggle flows offline when setting team status to trial

src/export/digitalPlanning/schemas/application/schema.json, src/export/digitalPlanning/schemas/application/types.d.ts, src/export/digitalPlanning/schemas/preApplication/schema.json, src/export/digitalPlanning/schemas/preApplication/types.d.ts
Per https://github.com/theopensystemslab/digital-planning-data-schemas/tree/dist/v0.7.4/schemas
=> chore: bump ODP Schema v0.7.4

src/utils/feeBreakdown.test.ts, src/utils/feeBreakdown.ts
We now calculate a single `reductionOrExemptionAmount` using the same formula (not 100%) for more flexibilty, better matching real life service content. See this thread: https://opensystemslab.slack.com/archives/C07F7215W7P/p1746551691064409?thread_ts=1746524633.032529&cid=C07F7215W7P
=> fix: fee breakdown should account for non-100% exemptions

.github/workflows/test.yml
Resolves https://github.com/theopensystemslab/planx-core/security/code-scanning/6
=> fix: Add permissions to GHA workflow

package.json, pnpm-lock.yaml, vitest.config.ts
Fixes https://github.com/theopensystemslab/planx-core/security/dependabot/24
=> fix: CVE-2025-46565

package.json, pnpm-lock.yaml
- Bump repo and repo variable `PNPM_VERSION` to v10.10.0
- Implemented in https://github.com/theopensystemslab/planx-new/pull/4661
=> chore: Upgrade repo to pnpm v10

src/types/flow.ts
Supports https://github.com/theopensystemslab/planx-new/pull/4770
=> feat: add `TemplatedNodeData` type

pnpm-lock.yaml
Regenerate lockfile to fix https://github.com/theopensystemslab/planx-core/security/dependabot/26
=> fix: CVE-2025-5889

src/export/bops/utils/index.ts, src/export/bops/utils/schema.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/5014
=> chore: Update types for getSchemaProposalDetails()
