theopensystemslab/planx-core

- jest.config.ts
- package.json
- src/helpers.test.ts
- src/helpers.ts
- src/index.test.ts
- src/index.ts
- src/logic.test.ts
- src/logic.ts
- src/mocks/complex-flow-breadcrumbs.ts
- src/mocks/section-flow-breadcrumbs.ts
- src/mocks/simple-flow-breadcrumbs.ts
- src/types.ts
- tsconfig.check.json
This PR adds the groundwork for a rich set of logic queries using normalized data structures.
By turning the graph into an ordered array with a rich set of data in each node, querying the flow becomes quite straightforward. `NormalizedFlow` adds enough data to each node to enable forward and backward traversal and other query functions (i.e sections). Although this data structure could be quite large for very big flows, the operations should be fairly inexpensive and fast with a structure like this.
This also starts to move the data structures towards nicer serialization (e.g. component type has a string name and a helper lookup function).
There are a lot of test data changes here - the meat of the change is visible in the [type declarations …
> feat: Add normalized flow

- src/document-templates.ts
- src/export/oneApp/index.ts
- src/index.ts
When handling templates, we currently derive everything from a `sessionId`. A new function has been added to allow us to fetch template names from a `sessionId`.
Relies on db changes made in https://github.com/theopensystemslab/planx-new/pull/1553
> feat: GetTemplates for flow and session

- src/session.ts
A submission to Uniform via staging failed with the following error - 
```{
"data": {
"message": "{\"error\":\"Failed to send to Uniform. Error: Failed to generate OneApp XML. Error - Error: field \\\"flowId\\\" not found in type: 'lowcal_sessions': {\\\"response\\\":{\\\"errors\\\":[{\\\"extensions\\\":{\\\"path\\\":\\\"$.selectionSet.lowcal_sessions_by_pk.selectionSet.flowId\\\",\\\"code\\\":\\\"validation-failed\\\"},\\\"message\\\":\\\"field \\\\\\\"flowId\\\\\\\" not found in type: 'lowcal_sessions'\\\"}],\\\"status\\\":200,\\\"headers\\\":{}},\\\"request\\\":{\\\"query\\\":\\\"\\\\n      query GetSessionById(\\\\n        $id: uuid!\\\\n      ) {\\\\n        lowcal_sessions_by_pk(\\\\n          id: $id\\\\n        ) {\\\\n          data\\\\n          flow_id: flowId\\\\n …
```
> fix: `GetSessionById` query syntax

- src/flow.ts
- src/index.ts
- src/payment-request.test.ts
- src/payment-request.ts
- src/session.ts
- src/types.ts
Payment requests can only be created for flows with a pay component. This adds a lookup for the "amount" passport key from the pay component and add it to sessionPreviewKeys if it exists and fails the payment request creation if not.
> feat: add payment amount to payment requests

- src/export/oneApp/OneApp.test.ts
- src/export/oneApp/schema.ts
A recent Uniform submission has failed as applicant contact details were missing (email and telephone).
Our LDC service allows this, but the OneApp schema (and our Zod schema which represents it) does not.
This change allows applicant contact details to be optional, as long as they are supplied for an agent. I'm not totally sure if Uniform is validating this - I suspect it's not an issue but just something that might still cause a failure following this change.
> fix: Allow optional email and telephone for applicants

- src/logic.test.ts
- src/logic.ts
- src/mocks/section-flow-breadcrumbs.ts
- src/types/flow.ts
When sorting a flow, it seems useful to track which node belongs to which section. This PR adds an optional `sectionId` field to each node in a sorted flow.
> feat: Add optional `sectionId` to sorted flow nodes

- src/graphql.ts
- src/index.test.ts
- src/index.ts
This method allows a public client to access data for a given session by amending the GraphQL headers of the client.
> feat: Add authorizeSession to graphql client

- package.json
- pnpm-lock.yaml
- src/requests/application.ts
- src/requests/flow.ts
- src/requests/index.ts
- src/requests/payment-request.ts
- src/requests/session.ts
- src/requests/team.ts
- src/requests/user.ts
- src/types/application.ts
- src/types/index.ts
- src/types/session.ts
The purpose of this PR is to introduce some new request functions used in e2e testing.
Rather than adding to an ever-growing set of exported request functions in one file, here I'm introducing namespaced clients. Each client exposes a nice simple interface within a namespace of the main client (e.g. `client.session.lock("123")`).
Used by https://github.com/theopensystemslab/planx-new/pull/1743
> feat: Add namespaced clients

- src/requests/payment-request.ts
Better handling to help address issue described here - https://trello.com/c/2n0EJ3wA/1635-invite-to-pay-epic#comment-6481a3db0d31432020c497bf
Implementation and tested in https://github.com/theopensystemslab/planx-new/pull/1773
> fix: Check payment has not already been initialised before generating payment request

- src/requests/index.ts
If we run a GraphQl `_in` query on an `undefined` value, we get the following error - 
```json
{
"errors": [
{
"extensions": {
"path": "$.selectionSet.project_types.args.where.value._in",
"code": "validation-failed"
},
"message": "expected a list, but found null"
}
]
}
```
I can currently hit this error when hitting the `/resume-application` endpoint for my OSL email.
> fix: Handle missing raw project types

- src/export/bops/index.ts
- src/export/bops/mocks/payload.ts
- src/export/bops/tests/flags.test.ts
- src/export/bops/tests/proposalDetails.test.ts
Interim fix for #49 until we have confirmation from BOPS team. 
This helps our submissions issue without breaking any assumptions or references they have to the field name existing for grouping.
> fix: set `portal_name` to empty string temporarily in BOPS export

- src/export/bops/index.ts
- src/export/bops/mocks/payload.ts
- src/export/bops/model.ts
- src/export/bops/tests/flags.test.ts
- src/export/bops/tests/proposalDetails.test.ts
BOPS devs confirmed they've made the switch over to `section_name` earlier today :heavy_check_mark:  
~optimistically queuing this up, but still waiting on go-ahead from BOPS devs here~: https://opendigitalplanning.slack.com/archives/C0182MVK4AW/p1688114717054409
`section_name` is now included in payloads for services with sections and offers a more meaningful grouping of questions than `portal_name` did, and is less expensive to compute which should be a small boost for processing submissions.
> fix: remove `portal_name` from BOPS export format

- src/templates/docx/LDCPTemplate.ts
- src/templates/mocks/exampleLDCP.json
Per feedback here: https://trello.com/c/MYuIMAkf/2506-add-description-to-ldc-application-form
There isn't an equivalent field on LDCE. This field will _not_ be redacted.
**Before:**
**After:**
> fix: map `proposal.description` to LDCP doc template

- package.json
- pnpm-lock.yaml
- src/templates/generateExamples.ts
- src/templates/html/Main.tsx
- src/templates/html/application/ApplicationHTML.tsx
- src/templates/html/map/Map.tsx
- src/templates/html/map/MapHTML.tsx
- src/templates/index.ts
- src/templates/mocks/ukBoundary.ts
- Requires that an extent be passed to map and HTML templates
- Uses Bucks as an example extent GeoJSON (see attached generated examples)
- Re-enables map pan and zoom
📂  [Examples.zip](https://github.com/theopensystemslab/planx-core/files/12352683/Archive.zip)
Currently live on this environment - https://github.com/theopensystemslab/planx-new/pull/2099
> feat: Add team boundary argument to map and html creation

- src/requests/flow.ts
- src/requests/team.ts
- src/requests/user.ts
To be implemented in https://github.com/theopensystemslab/planx-new/pull/2220 to help tear down permission-based tests.
> feat: Add more `_destroyAll()` helpers

- jest.config.ts
- jest.setup.js
- src/requests/index.ts
When running `pnpm build` in `planx-new/editor.planx.uk` the following Webpack error was being thrown - 
```
Module build failed: UnhandledSchemeError: Reading from "node:assert" is not handled by plugins (Unhandled scheme).
```
The simple solution here is just to drop the `assert()` statements here which aren't essential.
> fix: `node:assert` error causing failing builds in `planx-new`

- tsconfig.json
- tsconfig.types.json
Recent builds of `planx-new` are failing on Vultr due to JavaScript running out of heap memory when running the `pnpm build` step of `planx-core`. It's actually the TypeScript compilation step that's causing this to fall over. Recent changes in https://github.com/theopensystemslab/planx-core/pull/79 lead to this breaking change, notably - incorrectly glob patterns in the `exclude` list of `tsconfig.json` which means that very very large flows are being needlessly type-checked at build time.
Two massively helpful resource to problem solve this one - 
- https://carlrannaberg.medium.com/overcoming-javascript-heap-out-of-memory-error-during-typescript-compilation-in-a-mui5-react-21396cc8a4e1
- https://github.com/microsoft/TypeScript/wiki/Performance#writing-easy-to-compile-code
Running `pnpm …
> fix: Profile `tsc`, fix `tsconfig.json`

- src/export/digitalPlanning/model.test.ts
- src/export/digitalPlanning/model.ts
- src/export/digitalPlanning/schema/schema.json
- src/export/digitalPlanning/schema/types.d.ts
- src/requests/session.ts
- src/types/session.ts
- Copy over release v0.1.1 of the Digital Planning Application schema and auto generate types
- Update mapping to remove `metadata.service.publishedFlowId` 
- Checking all production submissions in October 2023 to see if they validate or not and fixing errors:
| `sessionId` | Type | Validates | Notes
|---|---|---|---|
| `d7cf2da2-fb4c-4930-841d-33e4ed23d905`  | Bucks LDC  | :heavy_check_mark:   | | 
| `fe6fa607-ee22-4e05-b4e0-382d5d00b9e6`  | Gloucester PP  | :heavy_check_mark:  | |
| `2e3cabab-633d-4869-a5de-0752c612ac14` | Gloucester PP | :heavy_check_mark: | |
| `faa32d08-246d-4510-97ef-689abb2b36dc`  | Southwark LDC | :x: | Custom flag & result text raises enum type error |
| `97c4fe80-2862-4e7e-9e0c-3786ed31a5d6` | Southwark LDC | :x: | Uploaded `proposal.drawing.locationPlan` …
> fix: use Digital Planning Application v0.1.1 and fix validation errors

- jest.config.ts
- package.json
- src/export/bops/index.ts
- src/export/bops/tests/addressInput.test.ts
- src/export/bops/tests/contactInput.test.ts
- tsconfig.build.json
- tsconfig.json
- tsconfig.types.json
- Follow on from https://github.com/theopensystemslab/planx-core/pull/78
- Removes all `implicitAny`s apart from those in `src/export/digitalPlanning/model.ts`
- Write `Passport.get()` method to replace the placeholder `Passport.generic()` (see https://github.com/theopensystemslab/planx-core/pull/78#discussion_r1363887300)
- Test TS compilation on Pizza
- Rebase / merge / cherry-pick https://github.com/theopensystemslab/planx-core/pull/68 to move things forward there
> chore: More type tightening

- src/requests/user.ts
There's a few ways to solve this one, but this feels like a good balance of visibility and pragmaticm. 
For reference - we handle this with a DB trigger for `lowcal_sessions`
I've updated any email records on production to be all lowercase.
> chore: Lowercase email on user creation

- src/export/digitalPlanning/model.ts
- src/export/digitalPlanning/schema/schema.json
- src/export/digitalPlanning/schema/types.d.ts
- adds schema v0.1.2 & generates new types
- improves passport mapping throughout (especially more conditional checks to omit optional properties rather than include as `{}`)
> feat: update digital planning data schema mappings

- src/models/session/logic.test.ts
- src/models/session/logic.ts
Recent submissions have been causing the API to crash, due to it running out of CPU. [We've bumped this a few times](https://github.com/theopensystemslab/planx-new/pull/2345) but are still seeing huge spikes on submission. 
[Profiling](https://nodejs.org/docs/latest-v18.x/api/inspector.html#cpu-profiler) `computeBOPSParams()` which the the main function which reads a session and flow and converts to various formats points towards `searchNodeEdges()` as being the leading cause.
`searchNodeEdges()` is currently doing a whole lot - 
- Recursively navigating through the entire flow
- Iterating through `breadcrumbIds`
- Reducing and generating `answerData`
- Generating an `orderedBreadcrumb`
On the mock flow in tests, this is happening 420,000+ times 👀 
I did a fair bit of reading up on ways …
> feat: Optimise `sortBreadcrumbs()`

- src/requests/user.ts
Currently E2E tests are failing as `team1-teamEditor-user@example.com` !== `team1-teameditor-user@example.com` 🤦 
See https://github.com/theopensystemslab/planx-core/pull/175
> fix: Convert emails to lowercase on request to match insert

- src/templates/html/application/ApplicationHTML.tsx
Quick fix for now! We should revisit these template mappings more comprehensively later depending on trajectory of ODP schema & Nexus integration.
Bug reported here: https://opensystemslab.slack.com/archives/C5Q59R3HB/p1699268853384899
CSV & BOPS admin endpoints for the given `sessionId` generate fine, so the bug was isolated to this HTML template.
> fix: property site address should be optional in HTML templates

- src/export/digitalPlanning/model.ts
Was checking recent application payloads today (eg [admin endpoint for BOPS](https://api.editor.planx.uk/admin/session/6508e9bd-a50e-4621-b6d9-f9cd3e23a214/bops) compared to [admin endpoint for schema](https://api.editor.planx.uk/admin/session/6508e9bd-a50e-4621-b6d9-f9cd3e23a214/digital-planning-application) for the most recent Southwark LDC) and I noticed some unexpected 0s and undefineds in the new schema mapping. 
Confusingly, these still validate successfully but are false data - it's easy to overlook!
It seems most of these were introduced through the use of `generic<>` which I've removed here for now, in favor of the clunkier syntax `as <type>`. Very open to other suggestions.
Examples in the ODP schema repo are okay as I've been updating them section-by-section for a bit now (eg …
> fix: update passport <> ODP Schema mappings

- package.json
- pnpm-lock.yaml
- src/export/bops/index.ts
Replaces #213 
Please see this issue for context: https://github.com/markedjs/marked/pull/3103
> chore: Update marked to v11

- src/export/digitalPlanning/model.ts
- src/templates/generateExamples.ts
- src/templates/html/Main.tsx
- src/templates/html/application/ApplicationHTML.tsx
- src/templates/html/map/Map.tsx
- src/templates/html/map/MapHTML.tsx
- src/templates/index.ts
Since introducing title boundaries, we should ensure that any document templates that display the boundary: 1) have proper attribution and 2) explain the action the user took to planning officers.
`Overview.html` & `Map.html` will now always show a "Source" underneath the map image, and will conditionally render the second attribution title boundary on the map if the user accepted or amended it as their location plan. 
For example:
> chore: account for title boundaries in document templates

- src/templates/html/map/Map.tsx
It failed on the `style` tag :weary: 
Also cleaning up all buffer types which we use a bit inconsistenly between numbers/strings - Lit evaluates same / smartly but TS is picky !
> fix: map props need to include style and buffers should be numbers

- src/templates/html/map/MapHTML.tsx
The MapHTML was missing these OL CDNs, while the ApplicationHTML had them. Consistently using among both generated documents means the print dialog behaves consistently ! 
Before:
After:
> fix: ensure boundary HTML doesn't display print dialog

- src/requests/team.ts
- Create an empty `team_integrations` record on team creation
- Create an empty `team_theme` record on team creation
- Update arguments for `team.create()` to better reflect what is generally available at time of creation - make submission email optional. Boundary and reference code are also optional as not all teams will be local authorities (e.g. Templates, OSL, ODP, WikiHouse)
Implemented in https://github.com/theopensystemslab/planx-team-onboarding/pull/16 and https://github.com/theopensystemslab/planx-new/pull/2720
> feat: Create empty `team_theme` and `team_integrations` records on team creation

- package.json
- src/export/bops/index.ts
- src/export/digitalPlanning/model.ts
- src/export/oneApp/model.ts
- src/models/passport/passport.test.ts
- src/models/passport/passport.ts
- Uses a single method to read files from the passport
- Quick refactor before working on the wider file-type changes to add requested files to the ODP schema payload
> feat: Read file details from `Passport()` class

- src/export/digitalPlanning/model.test.ts
- src/export/digitalPlanning/model.ts
- src/models/passport/passport.ts
Cherry picked from https://github.com/theopensystemslab/planx-core/pull/291 to avoid rebasing too much!
- Adds and populates `metadata.service.file` to Digital Planning payload
- Adds a few test cases, certainly scope for more here!
> feat: Add `metadata.service.files` to DigitalPlanning payload 

- src/export/digitalPlanning/model.ts
Fixes schema validation error thrown here: https://opensystemslab.slack.com/archives/C4B0CKQ3U/p1707739712194959
These admin endpoints are useful in troubleshooting / id'ing the error:
https://api.editor.planx.dev/admin/session/dba890b5-793c-41ba-b7f1-8650788ff3dc/digital-planning-application
https://api.editor.planx.dev/admin/session/dba890b5-793c-41ba-b7f1-8650788ff3dc/summary
This one was a passport mapping error on our side:
- When the site contact is _not_ the applicant, we were previously looking for single text input `applicant.siteContact.name`
- But the flow uses a contact input which writes `applicant.siteContact.name.first` & `applicant.siteContact.name.last`
> fix: update `SiteContact` passport variables mapping

- src/export/digitalPlanning/model.test.ts
These were temporarily skipped while sequencing merges about document-type changes and we forgot to re-enable !
> fix: unskip schema tests

- src/export/oneApp/OneApp.test.ts
- src/export/oneApp/model.ts
Related to https://github.com/theopensystemslab/planx-new/pull/2804
Rather than making this an optional argument on the `buildSubmissionExportZip()` method like `includeDigitalPlanningSchemaJSON` - we can just include by default for supported application types (Uniform = always LDC) which will give councils more flexibility (eg retrieve the JSON from DMS rather than email inbox; not have to configure a service to send to all three possible destinations) and communicates to Idox that we're ready/able to be sending this new data format regardless of Nexus.
Once this is approved and merged to `main` along with 2804, I'll submit a test LDC on staging and get a council PO to confirm it can be received correctly via DMS and doesn't break before going to production.
> feat: include the ODP Schema as "application.json" in files sent to Uniform

- src/export/oneApp/OneApp.test.ts
- src/export/oneApp/model.ts
Reverts theopensystemslab/planx-core#309
Doesn't look hopeful that DMS will accept a JSON, and found out most folks' staging envs were either turned off or inaccessible and this isn't a necessary change, so probably not worth the test trouble.
> Revert "feat: include the ODP Schema as "application.json" in files sent to Uniform"

- src/export/digitalPlanning/index.ts
- src/export/index.ts
- src/export/oneApp/mocks/session.ts
- src/requests/payment-request.test.ts
- src/requests/payment-request.ts
- src/requests/session.ts
- src/types/session.ts
We call `$api.session.find()` when creating the export zip - and we want access to the flow slug for its' filename.
> fix: adjust `Session` type to include `flow.id` & `flow.slug`

- src/export/digitalPlanning/model.test.ts
- src/export/digitalPlanning/model.ts
- src/export/digitalPlanning/schema/schema.json
- src/export/digitalPlanning/schema/types.d.ts
Relies on https://github.com/theopensystemslab/digital-planning-data-schemas/pull/124
Parses the Calculate "help text" from applicable nodes and adds to the Planx service metadata for a given payload.
> feat: populate fee explanations in ODP Schema v0.4.1

- src/requests/session.ts
Followup from #328  - `DetailedSession` type is based on `Session` but was still fetching an outdated shape.  
This fixes my `createPaymentRequest` error popping up over here :heavy_check_mark:  https://github.com/theopensystemslab/planx-new/pull/2893
> fix: update `DetailedSession` type

- src/requests/team.ts
This field is actually required in order to generate a valid DigitalPlanning payload. Please see https://github.com/theopensystemslab/planx-new/pull/2918 for context.
> fix: Make `reference_code` mandatory

- src/export/bops/mocks/payload.ts
- src/export/bops/mocks/sessionData.ts
- src/export/digitalPlanning/mocks/lawfulDevelopmentCertificate.ts
- src/export/digitalPlanning/mocks/planningPermission.ts
- src/export/digitalPlanning/mocks/priorApproval.ts
- src/export/digitalPlanning/model.ts
Related to https://github.com/theopensystemslab/planx-new/pull/2854
Mostly just updates to mock data here besides populating `metadata.service` URL in ODP Schema - therefore we shouldn't merge this until publishing changes are live on Planx staging/production !
> chore: update any Editor `/preview` URLs to `/published`

- src/export/digitalPlanning/model.ts
Fixes validation error for https://planx.airbrake.io/projects/329753/groups/3768516899831389867
See original passport here: https://api.editor.planx.uk/admin/session/33181543-e0cd-4bb1-9a91-6e97a88834fc/summary
> fix: adjust `preApp.summary` passport mapping for ODP Schema

- src/templates/html/map/Map.tsx
We want to call `collapseAttributions` prop across `planx-new` instances of `<my-map />` for accessibility fixes, but `MapProps` need to be updated first.
Changes:
- Syncs `MapProps` to all possible values in latest web component release and sort ascending for readability
- Updates `string` types to exact enum values where possible for consistency
> chore: update MapProps

- src/export/digitalPlanning/model.ts
- src/templates/html/application/ApplicationHTML.tsx
- src/templates/html/map/MapHTML.tsx
Two small maintenance tasks related to submissions & doc templates:
- BOPS flagged that `planning.data.gov.uk` JSON entity links are now redirecting to `www.planning.data.gov.uk` so let's set that directly https://opendigitalplanning.slack.com/archives/C0182MVK4AW/p1712570743064369
- Document templates should use latest `@opensystemslab/map` release for accessibility improvements
> chore: update @opensystemslab/map package and planning.data source links

- src/types/gov-uk-payment.ts
- src/utils/govPayMetadata.test.ts
- src/utils/govPayMetadata.ts
- src/utils/index.ts
- Adds a `formatGovPayMetadata()` helper function with two responsibilities - 
- Format "Editor" data shape used in Edtior modal and saved in `flows` and `payment_request` tables (`Record<string, string | boolean | number>[]`) to data shape required by GovPay API (`Record<string, string>`)
- Validate that any dynamic variables (taken from Passport) ahere to the validation rules[ outlined by GovPay here](https://docs.payments.service.gov.uk/reporting/#add-more-information-to-a-payment-39-custom-metadata-39-or-39-reporting-columns-39)
- Moves shared types to `planx-core`
Currently, we have a simpler helper function (`formatMetadata()`) duplicated in Editor and API projects - it's a one-liner that just transforms from shape to shape. 
As we now need the additional logic to both read from the …
> feat: `formatGovPayMetadata()` helper

- src/requests/payment-request.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/3015
This PR ensures that default values are populated into the database when a payment request is created, as required. Previously this was being done on the API and defaults were being sent to GovPay only.
> fix: Ensure default value for metadata are populated to DB

- src/requests/payment-request.ts
- src/utils/govPayMetadata.test.ts
- src/utils/govPayMetadata.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/3038, please see this PR for context.
> chore: Add `paidViaInviteToPay` argument to `formatGovPayMetadata()`

- src/requests/team.ts
Corresponding planx-new migrations coming soon
This will be one per council, not one per environment _and_ council.
> chore: add `powerAutomateAPIKey` type to team integrations

- src/export/digitalPlanning/model.ts
- Fixes minor typos for `interest` & `declaration`
- Better mapping for the `owners` discriminate union type
> fix: minor typos in ownership schema mapping

- src/export/digitalPlanning/model.ts
See thread here (this has only occured on test env, not production): https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1715963778547149
Previously our passport mappings only checked for `_constraints` key which is populated based on Planning Data fetch.
Now this adds an extra fallback check to map from `property.constraints.planning` in cases of manual user answers (eg see this session's passport: https://api.editor.planx.dev/admin/session/74068ec3-2e9c-408a-ac6f-7832d1eb011f/summary)
> fix: account for manually answered planning constraints in ODP Schema generation

- src/requests/flow.ts
- src/types/flow.ts
Please see https://github.com/theopensystemslab/planx-new/pull/3170 for context.
This PR adds a helper method to toggle the status of the flow. This is used in E2E tests, and will be called by Editors in the frontend.
> feat: Setup `flow.setStatus()` function

- src/export/digitalPlanning/model.ts
This staging LDC failed because we have `data.applicant.ownership.owners[0].noticeGiven` = `"true"`, when it should be a proper boolean!
https://api.editor.planx.dev/admin/session/e42c9ebc-039f-4609-a7df-3c98f23e7d53/digital-planning-application?skipValidation=true
> fix: ensure owners `noticeGiven` is correctly cast to boolean

- src/export/digitalPlanning/model.ts
Based on feedback from August: 
> Came across some major inconsistency around start.date / started.date / completed.date / completion.date / finish.date etc.
>
> I changed that all to (for both intended and actual dates as they're mutually exclusive):
> - proposal.completed.date
> - proposal.started.date
>
> In the schema and content wherever I saw it.
Using our previous values as fallbacks still while we wait for service publishing to catch up!
> fix: update started & completed date mappings for ODP Schema

- src/export/oneApp/mocks/session.ts
- src/requests/payment-request.test.ts
- src/requests/session.ts
- src/types/session.ts
``InviteToPayData`` & ``InviteToPayMocks`` from **planx-new** are using the ``Session`` type when building the variables for the email templates. In order to use the new ``name`` column as the ``sessionName`` I need to update this ``Session`` type.
> feat: Adding "Name" to the "Session" type for Email Templates 

- src/export/digitalPlanning/model.ts
Prior Approvals now go through the `london-data-hub` flow too
> chore: update schema passport mappings so that Prior Approvals set GLA requirements

- pnpm-lock.yaml
Lockfile version was v9, should be on v6 for pnpn 8.6.6
Possibly / probably caused by a `pnpm i` somewhere in this repo with the wrong version of pnpm locally?
Update: Looks like this was incorrectly generated in this PR - https://github.com/theopensystemslab/planx-core/commit/56da417450d8f23252a0a697ec9887c027b423f9
> fix: Broken lockfile

- src/models/passport/passport.ts
- A recent submission fails to generate a `.zip` file as some of the URLs returned by `Passport().getFileURLs()` return as `undefined`
- This means that the submission cannot be generated
- Source: https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1719915590451399 (ODP Slack)
This is happening as some file upload breadcrumbs return with a status of `"error"`. See sanitised example below of fragment of invalid passport
```json
{
"data": {
"nodeIdOfFileUploadComponent": [
{
"url": "https://api.editor.planx.uk/someUrl/test.pdf",
"filename": "test.pdf",
"cachedSlot": {
"id": "yGcR1uDwJ0zxPJ-ftY4GQ",
"url": "https://api.editor.planx.uk/someUrl/test.pdf",
"file": {
"path": "test.pdf",
"size": 3431233,
"type": "application/pdf"
},
"status": "success",
"progress": 1
}
},
{
"filename": …
```
> fix: Don't allow undefined file URLs

- src/utils/digitalPlanningSchema.test.ts
- src/utils/digitalPlanningSchema.ts
- src/utils/index.ts
**Problem:**
- We define "enums" in the Digital Planning Data Schemas repository that are converted into a TypeScript type that then generates the schema.json file
- We import that schema.json file in this repository, and regenerate types based on it, but it's difficult to get back to the plain original dictionary enum variables. 
- We want to access those enum variables, not the types, to do simple validation checks on publish in the Planx Editor (eg "is every `fn` set by a FileUpload or FileUploadAndLabel component supported in the `FileType` definition of the ODP Schema?")
**Changes:**
- Define and make available a few simple utility methods to parse the `schema.json` file and return either a list of the passport values associated with a definition, or the original value/description …
> feat: get and export original enum values from json schema spec 

- src/requests/team.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/3422
> feat: Update `team.create()` to match new table structure

- src/export/digitalPlanning/model.test.ts
- src/export/digitalPlanning/model.ts
- src/requests/session.ts
- src/requests/team.ts
- src/types/session.ts
- Follow up to #448 
- Fixes a few things missed in this PR
- Proper handling of camelCase → snake_case
- Updated query when building DPA payload
> fix: Remove duplicated `referenceCode` from `CreateTeam` query

- src/export/bops/index.ts
- src/types/component.ts
This PR sets up work to introduce a new @planx component called **MapAndLabel**.
Following the steps set out here: https://github.com/theopensystemslab/planx-new/blob/main/editor.planx.uk/docs/adding-a-new-component.md
I have added MapAndLabel as an enum for the ``ComponentType``
I tried to follow current pattern of enums and placed in section alongside `FileUploadAndLabel`
> Feat: Add MapAndLabel as Enum to Component Type

- package.json
- pnpm-lock.yaml
Follows on from #465 
We can still add the `@mui/base` dependency, but we can't yet bump all the way up to MUI 5.16.x in planx-new without a fair number of cascading type changes to work out (see https://github.com/theopensystemslab/planx-new/pull/3467) - and we want MUI versions to stay consistent between planx-new <> planx-core.
Can revisit this one if downgrading the version here reverts progress on the ESM migration !
> build(deps): use MUI 5.15.10 for planx-new build

- src/requests/team.ts
To enable work being carried out in planx-new: https://github.com/theopensystemslab/planx-new/pull/3483
I want to retrieve the `domain` when fetching a team from the database, so it can be shown to the user in the new Links dialog box
> feat: Adding domain to the getTeamBySlug query

- src/requests/team.ts
- src/types/team.ts
I am adjusting team types and queries to suit the new location of `submission_email` created here: https://github.com/theopensystemslab/planx-new/pull/3554
This is to complete this Trello Ticket: https://trello.com/c/dVsTQpZZ/2984-allow-editors-to-see-update-their-teams-submission-email-in-team-settings-form
This adjustment should help the updating and maintaining of `submission_email` by teamAdmins.
> feat: adjust queries and types for new `submission_email` DB location

- src/requests/team.ts
Remove `$submissionEmail` variable type from mutation to allow planx-new to add `submissionEmail` as argument passed into `createTeam()`
This fix enables the planx-new e2e regression fix.
https://github.com/theopensystemslab/planx-new/pull/3613
> fix: Fix CreateTeam mutation for submission email

- src/requests/team.ts
- src/types/team.ts
I am tidying up work done on submission email, where it was moved from the ``teams`` table to the `team_settings`` table
Changes focused on removing old fields and switching from ``NotifyPersonalisation`` in the type to ``TeamContactSettings`` and using `Pick` to pull them from the ``TeamSettings`` type. This felt right and in line with other changes.
> refactor: submission email tidy up

- src/types/flow.ts
- Adds optional property `tags` to the `Node` type
- Also exposes the list using `as const` so that we have the values at runtime (e.g. to populate a select or other UI component)
This is intentionally not held in `Node.data.tags` as `data` is using `Value` which, while accurate, is tricky to work with. I'd be keen to not expand this further, and actually property type the graph in a single place. Something I'm very keen to look at soon as I'm really feeling the limitations of having `data: any` recently! Once this is done, I don't think there's any reason we couldn't add `tags` into `data`.
I'm aware that `Node` is also defined in the frontend, and doesn't yet use this type - I'll take a look at this next.
> chore: Add tags property to Node

- src/requests/team.ts
This was added to try and fix a bug with moveFlow, but it didn't fix in the way expected.
Currently fixed with another solution but may revisit for longer term fix.
> fix: remove sub-email from getByTeamSlug

- src/requests/team.ts
Adding new query to retrieve TeamSettings only.
In response to `GetBySlug` changing to not return `submission_email` due to column permission changes
> feat: new GetTeamSettings query

- src/requests/team.ts
In my last commit for the previous PR, we changed the query so it pulled directly from the `team_settings` table rather than the `teams` table:
```diff
const response: { teamSettings: TeamSettings[] } = await client.request(
gql`
query GetTeamSettings($slug: String!) {
++      team_settings(where: { team: { slug: { _eq: $slug } } }) {
--       teams (where: { slug: { _eq: $slug } } }) {
--       teamSettings: team_settings{
boundaryUrl: boundary_url
...
submissionEmail: submission_email
}
}
`,
{ slug },
);
```
But, when I made this change, I forgot to redefine the table to a proper casing `teamSettings: team_settings` which led to issues in what this was returning as the return is:
```ts
return response.teamSettings[0];
```
> fix: Get Team Settings response fix

- src/models/result.ts
- src/types/flags.ts
- src/types/flow.ts
Follow up to https://github.com/theopensystemslab/planx-core/pull/508
This PR changes the `tags` field to be a child of `data`. I've resolved the union issue with `Value` in planx-new here - https://github.com/theopensystemslab/planx-new/pull/3716
Using this method I've got a crude end-to-end solution working locally. PR incoming later today!
> feat: Add tags field to node data (take 2)

- src/export/csv/index.ts
- src/export/index.ts
Fixes #help-issues report from Friday afternoon: https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1728640257349149
Depending if the applicant self-paid or invited-to-pay, the payment info will be stored differently. We've been correctly accounting for this in the ODP Schema ([eg here](https://github.com/theopensystemslab/planx-core/blob/main/src/export/digitalPlanning/model.ts#L686-L698)) but NOT the CSV/Overview HTML formats and the reference number in invite to pay cases was failing to populate.
This fix correctly accounts for invite to pay cases, but ideally in the near future we'll do a larger refactor to generate the CSV & Overview HTML from the ODP Schema directly so we can remove these duplicated bespoke messy mappings!
> fix: ensure Gov Pay reference is set for invite to pay applications in overview HTML and CSV

- src/utils/encryption.ts
- Wraps `decrypt()` in a try/catch
- Currently, if decryption fails, an unhandled exception brings down Express
- This now ensures it's handled gracefully, and the consumer needs to check the existence of they keys (the function still maintains it's signature of returning `string | undefined` for a secret)
- Make a secret invalid, e.g. populate encrypted GovPay token as plaintext string `"abc123"`
- Try to make payment
- Graceful error handling in application, Docker logs capture issue
- Example flow here on Pizza with an invalid GovPay key - https://3848.planx.pizza/epsom-and-ewell/test-pay-failure/published?analytics=false
> chore: Error handling for `decrypt()`

- src/types/roles.ts
As part of the work here: https://trello.com/c/EfaEQRzK/2441-create-a-demo-workspace
I wanted to add a new team role for demo users. Assigning this to `TeamRole` over `UserRole` as `TeamRole` is used when fetching a users list of teams and it will make it easier in the future to promote them.
One of the connected future bits of work will be to alter the `is_staging_only` column for the demo users. 
I would be interested to know if we think this is the right approach. I am slightly hesitant because I feel the `demoUser` role is a global role that would restrict what a user can do and see, although the restrictions only really apply to a single team within PlanX, the "Demo" team, so I've started off with it as a `TeamRole` applied in the `team_members` table of the database.
> feat: add `demoUser` to `TeamRole` type

- src/export/digitalPlanning/model.ts
From August:
> Schema currently expects a `proposal.description` for LDCs. During our review we learned that LDCs have project and app type specific requirements, so that we now capture these as various `.details` inputs instead.
> - if `application.type` is `ldc.proposed`: concatenate `proposal.buildingOperations.details` and `proposal.changeOfUse.details` and map result to `proposal.description`
> - if `application.type` is `ldc.existing`: concatenate `proposal.existingWorks.details` and `proposal.existingUse.details` and map result to `proposal.description`
> 
> Both app types can have one of or both of these, and it's never both app types, so maybe ignore the app type condition and concatenate all available `.details`?
In a future release, it'd be ideal to break these fields out …
> chore: update ODP Schema `proposal.description` mappings based on new LDC inputs

- src/models/session/logic.test.ts
- src/models/session/logic.ts
- src/models/session/mocks/flow-with-internal-portals.ts
- Fixes issue described here https://opensystemslab.slack.com/archives/C01E3AC0C03/p1730805531747509 (OSL Slack)
- Creates a stack of portal ids when indexing nodes
- Add to the stack when we hit a portal
- Remove from the stack when we exit
- This means that we now correctly assign the `internalPortalId` to all indexed nodes.
Implemented in https://github.com/theopensystemslab/planx-new/pull/3914
> fix: Correctly track portal IDs when indexing nodes

- src/export/bops/index.ts
- src/export/bops/tests/proposalDetails.test.ts
Simpler solution to #554, implemented here https://github.com/theopensystemslab/planx-new/pull/3918
Per bug report here https://opensystemslab.slack.com/archives/C01E3AC0C03/p1730907777602279
Questions without `edges` (aka "sticky note" questions) now leave a breadcrumb per the new automation logic, whereas before they didn't. They were being correctly filtered out of the Result & Review pages in-service, but incorrectly included in the submission documents.
> fix: filter questions without responses out of generated docs (take 2)

- src/export/bops/index.ts
- src/export/bops/schema/utils.ts
- src/export/bops/tests/proposalDetails.test.ts
- Ensures that when a payload contains a `List` or `Page` component, that the values are parsed
- These parsed values are used in the following ways - 
- Responses in `DigitalPlanningPayload`
- Responses in CSV
- Responses in generated HTML docs
There's a lot of room for refactors and improvements in this area of the code base, but I've tried to make this an additive change here instead of starting to untangle too much at the same time.
> feat: Generate `QuestionAndResponse[]` for `List` and `Page` components

- src/types/feeBreakdown.ts
- src/utils/feeBreakdown.test.ts
- src/utils/feeBreakdown.ts
- src/utils/index.ts
- Changes logic to now rely on on `application.fee.includesVAT` (boolean) instead of `application.fee.vat` (number)
- This means we are relying on Editors to tell us if the fee in inclusive of VAT, but does not rely on them to make the calculation themselves
- Based on decision from Monday's fee breakdown show & tell
This doesn't cover the cases where teams require a VAT amount to be included within their GovUK Pay metadata. In these cases they will still need to calculate it as a passport variable, and add it to the metadata fields. It's probably worth getting teams to adopt this approach there as well but I'm intentionally avoiding this here in order to focus on the fee breakdown feature.
>  feat: Calculate VAT using `getFeeBreakdown()`

- src/requests/payment-request.test.ts
- src/requests/payment-request.ts
- src/types/payment-request.ts
- Generates a fee breakdown for an "invite to pay" session
- Persists to DB as part of the `payment_requests` table
- Implemented in planx-new here - https://github.com/theopensystemslab/planx-new/pull/4057
> feat(itp): Handle fee breakdown

- src/export/digitalPlanning/model.ts
Small refactor to use a single passport mapping for fee breakdown - this should mean that we could add new values (e.g. exemptions, reductions) in a simpler manner in future.
A nice enhancement here would be to also grab the fee categories in `getFeeBreakdown()`
> feat: Use `getFeeBreakdown()` util for generating payload

- src/requests/payment-request.ts
Small tidy up that should be merged and deployed after https://github.com/theopensystemslab/planx-new/pull/4058 hits production. 
No rush here as the current functionality will always work.
> chore: Remove redundant `getPayNode()` function

- src/export/digitalPlanning/mocks/flows/notificationOfCommencement.ts
- src/export/digitalPlanning/mocks/notificationOfCommencement.ts
- src/export/digitalPlanning/model.test.ts
- src/export/digitalPlanning/model.ts
- Correctly maps flows without a pay component to `ApplicationFeeNotApplicable`
- Adds test case for discretionary services without a pay component
> feat: Update check for pay component

- src/export/bops/index.ts
- src/export/digitalPlanning/model.ts
- src/export/oneApp/model.ts
Sessions submitted before yesterday that haven't been downloaded by council partners are:
- Failing to display maps
- Were omitted from "sessions" update in script because they aren't "active"
So, I think these fallback variables should allow both old & new submission documents to correctly display
> fix: maps should fallback to old data fields for legacy sessions

- src/requests/flow.ts
- add `setSummary` and `setLimitations` to `FlowClient` for updating the short summary in the ReadMePage.
This PR is a pre-requisite for: https://github.com/theopensystemslab/planx-new/pull/4145 and is associated with [this Trello ticket](https://trello.com/c/2FMdl5c3/3159-add-a-description-field-like-a-readme-page-for-all-flows).
> feat: add new flow methods for ReadMePage work

- pnpm-lock.yaml
Fixes https://github.com/theopensystemslab/planx-core/security/dependabot/14
`pnpm why unidici` now logs a version which is not effected by the above issue - 
```sh
➜  planx-core git:(dp/CVE-2025-22150) ✗ pnpm why undici
Legend: production dependency, optional only, dev only
@opensystemslab/planx-core@1.0.0 /Users/dafyddllyr/Code/planx-core
dependencies:
cheerio 1.0.0
└── undici 6.21.1
```
> fix: CVE-2025-22150

- package.json
- pnpm-lock.yaml
Hitting some build issue in `planx-new` which references this import via `planx-core`. The package is deprecated and unused, here's what I've checked - 
- Library builds
- Library passes tests
- `pnpm examples` works
- No references in code to `@mui/base`
> chore: Drop deprecated `@mui/base` package

- src/requests/flow.ts
This brings E2E helpers in sync in functionality introduced here: https://github.com/theopensystemslab/planx-new/pull/4230
> feat: automatically publish newly created flows

- src/export/digitalPlanning/model.ts
We've had two reports of failing preApp payloads in two days. Both cases are using "send to email" (& very unlikely the .json which when fails blocks the whole zip). 
I think it's worth considering if we should temporarily turn off preApp validation based on two big factors:
- George & the service's team work on a "preApp template" is still ongoing and until rolled out there's going to continue to be variance and surprises per council
- BOPS is not actually accepting preApps yet (when they start, we'll _have to_ validate payloads - but it honestly doesn't matter for our current send to email users I think?)
> fix: temporarily `skipValidation` for preApps

- src/requests/flow.ts
Now that flows are published on create, we need to add additional cleanup steps to our E2E API regression tests. There will also now be instances of _more than one_ published flow associated with a flow during a single test, so it's ideal to have a `destroyPublishedAll` helper here. 
Currently failing with error: `Error: Foreign key violation. update or delete on table "users" violates foreign key constraint "published_flows_publisher_id_fkey" on table "published_flows"`
```
{
"response": {
"errors": [{
"message": "Foreign key violation. update or delete on table \"users\" violates foreign key constraint \"published_flows_publisher_id_fkey\" on table \"published_flows\"",
"extensions": {
"path":"$",
"code":"constraint-violation"
}
}],
"status":200,
"headers":{}
},
"request": {
"query": …
```
> chore: add `flow._destroyPublishedAll` helper for E2E tests

- src/utils/feeBreakdown.test.ts
- src/utils/feeBreakdown.ts
Please see https://opensystemslab.slack.com/archives/C07F7215W7P/p1739350959482879 for context (OSL Slack).
Negative reductions should not happen and would be indicative of a content error (something incorrectly marked as a reduction when it is not).
This just adds a guard for this edge case, which will result in the fee breakdown not displaying for an applicant.
> fix: Error handling for negative reductions

- package.json
- pnpm-lock.yaml
Reverts https://github.com/theopensystemslab/planx-core/pull/654
See thread https://opensystemslab.slack.com/archives/C01E3AC0C03/p1740474001199569 (experiencing cache issues locally, _as well as_ on GA now!)
> revert: use `@mui/material` v5.15.10 to match planx-new

- src/types/planning-constraints.ts
Adds an exported `const` `activePlanningConstraints` which replaces duplicated, very similar instances in planx-new - see https://github.com/theopensystemslab/planx-new/pull/4372
This ensures that in the future when new Planning Data layers are added, it's a single place to update !
> chore: refactor Planning Constraints types for single source of truth

- src/export/digitalPlanning/model.ts
Reverts theopensystemslab/planx-core#641
Camden is preparing to go live with pre-apps. See ticket: https://trello.com/c/K7qtyE1t/3259-resolve-validation-issues-for-pre-application-payloads
> Revert "fix: temporarily `skipValidation` for preApps"

- src/export/digitalPlanning/model.ts
Lambeth has been testing `approval.condition` applications this week & bumping up against schema validation issues due to GLA/`london-data-hub`, which this application type does not use. 
This was leading to "empty" invalid payload fields like this, whereas it should be omitting them entirely.
> fix: account for all application types without GLA specs in payload mappings

- src/export/digitalPlanning/mocks/planningPermission.ts
- src/export/digitalPlanning/model.ts
Flagged yesterday by Meera - see `proposal.parking` in this example payload https://api.editor.planx.dev/admin/session/23f28a34-8ec3-473c-ad69-92734deba1f4/summary which incorrectly populated as "0"s in actual `/digital-planning-application` shape (no validation error)
This change fixes the passport mappings - but still only for London councils. It's highlighted an additional gap in our underlying types that don't correctly account for non-GLA parking with uses a different/separate Planx List Schema https://github.com/theopensystemslab/digital-planning-data-schemas/blob/main/types/shared/Parking.ts - we'll pick up this in the next schema release, but I'm hopeful it shouldn't be an issue for any live services in the meantime.
> fix: updated `parking` mappings for ODP Schema

- src/export/bops/utils/index.ts
- src/export/bops/utils/mapAndLabel.ts
- src/export/bops/utils/schema.ts
- src/utils/feeBreakdown.test.ts
- src/utils/feeBreakdown.ts
- Uses Zod's `safeParse()` instead of `parse()` to allow us to `.flatten()` (format) errors into a more readable format
- The `safeParse()` pattern seems a little cleaner than wrapping `try/catch` blocks everywhere
- The default Zod error (a list of issues) is comprehensive, but hard to read - `.flatten()` gives a nicer format we can more easily match to the input object
- Docs: https://zod.dev/ERROR_HANDLING?id=formatting-errors
This steps from the following discussion - https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1744009225907769 (OSL Slack)
> chore: Use Zod's `safeParse()` instead of `parse()` for better error handling and formatting

- src/export/digitalPlanning/model.ts
- src/export/oneApp/model.ts
The service as a whole has a Pay component, but this single journey within it is not "fee carrying". See https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1744359684053329
> fix: account for `ldc.listedBuildingWorks` having application fee `notApplicable`

- src/export/digitalPlanning/model.ts
Context https://opensystemslab.slack.com/archives/C088K9ZL8EA/p1744369024067619?thread_ts=1744359684.053329&cid=C088K9ZL8EA
> fix: `ldc.listedBuildingWorks` application types won't have PP flagset

- src/requests/team.ts
Implemented in https://github.com/theopensystemslab/planx-new/pull/4605
The mutation requires that a strict boolean is passed in, it's not casting / inferring `false` based on a falsy value being passed in.
> fix: Use strict boolean in  `UpdateTeamSettings` mutation

- src/types/planning-constraints.ts
Wait until `v0.7.4` schema release to merge: https://github.com/theopensystemslab/digital-planning-data-schemas/pull/334
https://trello.com/c/frNeWkE4/3283-add-battlefields-to-planning-constraint-checks
> feat: add `battlefield` to planning constraints schema

- src/utils/feeBreakdown.test.ts
- src/utils/feeBreakdown.ts
See error report here https://opensystemslab.slack.com/archives/C07F7215W7P/p1746545457127259?thread_ts=1746524633.032529&cid=C07F7215W7P
> fix: preserve calculated fee = 0 in breakdowns

- src/types/flags.ts
This PR flips flag colours of the material change of use flagset to Not material change of use (Green) and Material change of use (Red). Editors expressed confusion about flag set colour, presumably due to misalignment with semantic meaning: MCOU is non-restrictive, MCOU is restrictive.
> chore: flip Material Change of Use flag colour

- src/export/digitalPlanning/model.ts
- src/export/digitalPlanning/schemas/application/schema.json
- src/export/digitalPlanning/schemas/application/types.d.ts
- src/export/digitalPlanning/schemas/preApplication/schema.json
- src/export/digitalPlanning/schemas/preApplication/types.d.ts
Adds `ward` to payload following on from https://github.com/theopensystemslab/planx-new/pull/4703
This version won't be live on BOPS staging until at least Friday, May 30 https://opendigitalplanning.slack.com/archives/C0182MVK4AW/p1748510113789459?thread_ts=1748341617.208289&cid=C0182MVK4AW
Will add support for third, independent "enforcement" schema in follow-up future PR.
> feat: ODP Schema v0.7.5 (application & pre-application only)

- src/export/bops/index.ts
- src/export/bops/tests/contactInput.test.ts
- src/export/bops/tests/payload.test.ts
See #help-issues report from Gateshead here https://opendigitalplanning.slack.com/archives/C0241GWFG4B/p1749033657201129
> fix: correct redaction for single-line `ContactInput` transformation in `proposal_details`

- src/types/flags.ts
This repeats the patterns used for `const NODE_TAGS` and `type NodeTags`, allowing us access to the underlying values as well as the types.
Implemented in https://github.com/theopensystemslab/planx-new/pull/4909
> chore: Export `FlagSet` values, not just types

- src/export/digitalPlanning/model.test.ts
- src/export/digitalPlanning/model.ts
Updates the `metadata.submittedAt` field for the Digital Planning Application payload to reference the original submission date, and not the current date.
(From memory) I believe the original motivation here was to acknowledge that user submission and PlanX submission are two distinct events - consumers should care about when _we_ send it (e.g. in the case of failures, retries etc).
I can't find a reference to this in the git blame, just this PR when it was introduced https://github.com/theopensystemslab/planx-core/pull/210
However, I think that this mental model of two submission events doesn't really hold up now that we have send to email and the ability to download from the Editor. Each time this happens a new (current) date is used for the payload 🐛 
If we were to generate a static …
> fix(digital-planning-application): Correctly map submitted date, not current date

- src/export/digitalPlanning/model.ts
Follow up and fix for https://github.com/theopensystemslab/planx-core/pull/831
The first time a payload is generated, `lowcal_session.submitted_at` will not be populated. In these cases, use the current time. For all future times the payload is generated, we can rely on the original submission date.
> fix: Use fallback value for `metadata.submittedAt`

- src/export/digitalPlanning/model.ts
For a pre application payload, a the `data.application.fee.payable` value is required. See schema definition here - https://github.com/theopensystemslab/digital-planning-data-schemas/blob/main/schemas/preApplication.json#L6890-L6915
Setting a fallback will mean that applications without fees will still generate valid payloads.
Currently, the `metadata` object handles this more gracefully - allowing either a `FeeExplanation` or `FeeExplanationNotApplicable`. It might be more consistent to consider a similar pattern within `data.application.fee` in future iterations.
> fix: Add fallback value for preApplication fee payable
